# Generated by Django 5.0.6 on 2024-07-17 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_menu_type_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu_type',
            name='title',
            field=models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=100),
        ),
    ]
