# Generated by Django 5.0.6 on 2024-07-17 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_menu_type_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=255, verbose_name='описание')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('image', models.ImageField(upload_to='menu_images/', verbose_name='Фото Меню')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 'Наши Меню',
            },
        ),
        migrations.DeleteModel(
            name='Menu',
        ),
        migrations.DeleteModel(
            name='Menu_Type',
        ),
    ]
