# Generated by Django 5.0.6 on 2024-07-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_menuitem_delete_menu_delete_menu_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание блюда')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена блюда')),
                ('image', models.ImageField(upload_to='menu_images/', verbose_name='Фото блюда')),
                ('category', models.CharField(max_length=50, verbose_name='Категория блюда')),
            ],
            options={
                'verbose_name': 'Блюдо',
                'verbose_name_plural': 'Блюда',
            },
        ),
        migrations.CreateModel(
            name='Menu_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('dinner', 'Dinner')], max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Тип Еды',
            },
        ),
        migrations.DeleteModel(
            name='MenuItem',
        ),
    ]
